### ISSUE TITLE
curl.h Dependency

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-server#22]
In the cluster-experimental branch, there is a new dependency on libcurl (the build error is for curl.h). Is the recommend way, for Ubuntu 16.04, to have this dependency?

`sudo apt install libcurl4-openssl-dev`

For docker builds that reference cluster-experimental, I see the same issue, a library dependency is missing for curl.h reference.

Thanks.

**Comment by davehorton** [comment]
yes, this is a new dependency on this branch -- I will check into the build error, thanks for pointing this out.  

Are you seeing an error when building using the checked-in Dockerfile?  I am able to build this branch on docker, and the Dockerfile does install this dependency as far as I see, so I just want to be clear

**Comment by davehorton** [comment]
FYI, as background, the reason for this dependency is that this branch supports an alternative method of connecting drachtio-srf node apps with the drachtio-server: *outbound connections*.

The typical (till now) method of connecting a drachtio-srf app to the server was to make an *inbound connection* by calling `srf.connect()`.  That is still supported, and in many cases is the preferred solution.  However, it is possible to configure the drachtio server to do an HTTP GET request to a specified endpoint when a SIP request arrives, in order either to receive simple routing instructions (e.g to proxy the call) or to provide a host:port endpoint where a  drachtio-srf app has called `srf.listen()`.  In the latter case, the drachtio server then connects to the drachtio srf app rather than vice versa (i.e an outbound connection).  The value of that is when you want to run multiple (different) apps against the same server to handle different types of traffic -- based on information in the SIP INVITE you can direct the call to the correct app for the given call scenario.

curl was added to enable the drachtio-server make these HTTP requests

**Comment by JimG777** [comment]
If I reference drachtio/drachtio-server (from Docker hub) in my Docker run command, it works. If I try to build my own image from davehorton/docker-drachtio-server, it fails with the curl.h reference error.

**Comment by davehorton** [comment]
ah ok.  The [Dockerfile](https://github.com/davehorton/drachtio-server/blob/cluster-experimental/Dockerfile) in this project is correct, and I need to update the other one.

**Comment by JimG777** [comment]
The curl dependency is handled in all the projects that I can see now. Thanks!
