### ISSUE TITLE
Stateless Proxy Support

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-server#32]
Would like to use multiple drachtio-servers to ship requests around. For example:

```
UE1         UE2       drachtioA       drachtioB
 |           |          |              |
 | INVITE (1)---------->|              |
 |           |          |(2)---------->|
 |           |          |              |
 |           |          |<----------(3)|
 |           |<------(4)|              |
 |           |          |              |
```

drachtioA handles most requests as a proxy and if coming from users from the internal network will forward the messages to another server, in this case, drachtioB. drachtioB acts as a Registrar/Proxy. In this case, UE1 and UE2 are registered with it. I want UE1 to send an INVITE to UE2 via drachtioA, then drachtioB, which will route the INVITE back through drachtioA to get to UE2. drachtioA would see the message coming from the external network and route to the internal client (UE2 address state would be in the application).

However, upon testing, I see the drachtio-server message "Discarding retransmitted request since we are a stateful proxy INVITE ...". Can drachtio-server be configured to be a stateless proxy? On a per message type request? Or is there a better way?

For drachtioA I am using drachtio Node.js app and for drachtioB I am using drachtio-srf.

**Comment by davehorton** [comment]
Currently there is no support for acting as a stateless proxy, only as a stateful proxy.

However, the scenario you outline should work fine as a stateful proxy.  The fact that drachtioA is seeing retransmitted requests from UE1 seems strange to me, because drachtioA would have sent a 100 Trying back to the INVITE from UE1, therefore UE1 should not need to retransmit INVITEs.

Unless, it is a different message that is being retransmitted?  A REGISTER or something?

If an INVITE, then I would like to look into why this is happening (logs etc).  If this is a non-INVITE then the question would be why is it taking so long for drachtioB to process and respond to the request

**Comment by davehorton** [comment]
any thoughts on this?  I'd like to help make it work as a stateful proxy, not sure why you are experiencing retransmits

**Comment by JimG777** [comment]
I was mulling over creating a simple (specific to my needs) stateless proxy... Didn't mean to delay. When I tested and described the original post, it certainly seemed like it was an INVITE retransmit. I will capture logs and upload, in case you are able to see something that can be fixed in this case. But I might not be able to get to this until later next week. Thanks for all you help as usual!

**Comment by JimG777** [comment]
I would like to close this issue, we are not planning to go in this direction at this time. Thanks!
