### ISSUE TITLE
Load balancing & high availability

### ISSUE THREAD

**Issue by ghafran** [davehorton/drachtio-server#52]
How would you recommend load balancing the server for horizontal scaling and higher availability?

Also, can the drachtio-srf client connect to multiple servers if they are load balanced?

Thanks.

**Comment by davehorton** [comment]
Most load balancing approaches involve putting a load balancing SIP proxy in front of your application servers, usually simply dispatching in a round-robin type of manner where the proxy uses OPTIONS ping or the like to determine whether an application is up.  You can do this with kamailio, using the dispatch module, or you could actually do it with another drachtio server, using a simple drachtio-srf app that both proxies incoming calls and OPTIONS pings the application servers.  

For more resiliency, there would be a pair of SIP proxy servers in active / standby configuration using something like haproxy.

Yes, one node.js app using drachtio-srf can connect to multiple servers.  You would need to explicitly call ‘connect’ for each server.  But I would recommend in this kind of environment configuring all of the drachtio application servers to use ‘outbound’ connections  (except perhaps the proxy, if you are using drachtio to front-end that).  See https://drachtio.org/docs/developer-guide#advanced-topics <https://drachtio.org/docs/developer-guide#advanced-topics> for details on this.  This makes more sense in a clustered environment — the connection is reversed, so that all of your drachtio servers connect to your application upon receiving an incoming call.  So you can run one or more application instances, scale them independently from your drachtio servers, and even use something like Kubernetes to expose one sip uri that will load balance application requests across your application instances.


On Sep 22, 2018, at 9:12 AM, ghafran <notifications@github.com> wrote:

How would you recommend load balancing the server for horizontal scaling and higher availability?

Also, can the drachtio-srf client connect to multiple servers if they are load balanced?

Thanks.

**Comment by ghafran** [comment]
That make sense, got some good info from the documentation. 

https://drachtio.org/docs/developer-guide#advanced-topics

I'm thinking of load balancing the servers using round-robin DNS with health checks, and use outbound connections from servers to srf applications via a web load balancer. This should get us a stateless setup.

Great work on this project!
