### ISSUE TITLE
assertion fails crash multiple cancel for the same invite

### ISSUE THREAD

**Issue by andrewvmail** [davehorton/drachtio-server#54]
Was just testing dockerize environment and pushing a few calls between two UAs both are WebRTC clients on mobile networks. After pushing several calls successfully i noticed a crash.

crash log: https://gist.github.com/andrewvmail/fbbdcd78e3ee8b6d4b7601121faf9e54

**Comment by davehorton** [comment]
It looks like the client sends an INVITE

```
018-10-11 01:38:41.464946 recv 2438 bytes from ws/[24.114.25.196]:42632 at 01:38:41.464186:
INVITE sip:mary@dev-sfo1-p2p-1.superfatcat.com SIP/2.0
Via: SIP/2.0/WS 14bjlup3m357.invalid;branch=z9hG4bK3069245
Max-Forwards: 70
To: <sip:mary@dev-sfo1-p2p-1.superfatcat.com>
From: <sip:bob@dev-sfo1-p2p-1.superfatcat.com>;tag=6efuij01qs
Call-ID: 3vur9ciggmj4cugku2hn
CSeq: 642 INVITE
```
then sends a CANCEL:
```
2018-10-11 01:38:57.083471 recv 342 bytes from ws/[24.114.25.196]:42632 at 01:38:57.083302:
CANCEL sip:mary@dev-sfo1-p2p-1.superfatcat.com SIP/2.0
Via: SIP/2.0/WS 14bjlup3m357.invalid;branch=z9hG4bK3069245
To: <sip:mary@dev-sfo1-p2p-1.superfatcat.com>
From: <sip:bob@dev-sfo1-p2p-1.superfatcat.com>;tag=6efuij01qs
Call-ID: 3vur9ciggmj4cugku2hn
Max-Forwards: 70
CSeq: 642 CANCEL
Content-Length: 0```
we send a 200 OK to the CANCEL and a 487 to the INVITE, which is all correct.

We then see a retransmit of the the CANCEL from the client for some reason:
```
2018-10-11 01:38:57.090348 recv 342 bytes from ws/[24.114.25.196]:42632 at 01:38:57.090104:
CANCEL sip:mary@dev-sfo1-p2p-1.superfatcat.com SIP/2.0
Via: SIP/2.0/WS 14bjlup3m357.invalid;branch=z9hG4bK3069245
To: <sip:mary@dev-sfo1-p2p-1.superfatcat.com>
From: <sip:bob@dev-sfo1-p2p-1.superfatcat.com>;tag=6efuij01qs
Call-ID: 3vur9ciggmj4cugku2hn
Max-Forwards: 70
CSeq: 642 CANCEL
Content-Length: 0
```
Now, since we are using websockets I do not think the client should be retransmitting (not to mention we have already send a 200 OK to the prior CANCEL).

What happens next, apparently, is that the app sends a 404 Response, presumably in response to this CANCEL but the transaction id is that for the INVITE.  This is what leads to the crash, because it triggers an assertion:

```
2018-10-11 01:38:57.095479 Client::read_handler read: efa95f0e-8d0e-46c6-8349-505be2e2609c|sip|0c90fa15-7e50-4e31-b867-564085910a7c|
SIP/2.0 404 Not Found
Call-ID: 3vur9ciggmj4cugku2hn
cseq: 642 CANCEL
from: <sip:bob@dev-sfo1-p2p-1.superfatcat.com>;tag=6efuij01qs
to: <sip:mary@dev-sfo1-p2p-1.superfatcat.com>
```

First, any idea why the client is retransmitting the CANCEL request?  That should only happen over a udp connection I think.

Secondly, is it possible to get any logs from the drachtio-srf side with DEBUG=drachtio:* for this crash?

**Comment by andrewvmail** [comment]
Hi Dave, 

Thanks for pointing this out, I did not consider client sending multiple cancel. So I found out why client is sending the 2 cancels. When using sipjs and I do session.cancel() then i stop the ua using ua.stop() there is a race or something, the cancel sends a cancel and the ua.stop also sends a cancel. I can just do a ua stop(). So bug reported there if its a bug..

And I cant get you the log for this crash but I can do a new one. I'll do that now and follow up with the logs.

**Comment by andrewvmail** [comment]
okay logs here, I masked some ip with xxx and username with bob and mary

drachtio-server: https://gist.github.com/andrewvmail/8d9f5a6907a6b7765e321c712af90ec0
drachtio-controller: https://gist.github.com/andrewvmail/df0dc5ed8a143c4e60444a92d8bd62d6

**Comment by davehorton** [comment]
can you retest with latest dractio-srf@4.3.7 ?  I believe I have checked in a fix there for this.  The framework should not be trying to send a 404 to the second CANCEL, which was leading to the assertion

**Comment by andrewvmail** [comment]
Okay tested and confirmed its fixed.

Thanks!
