### ISSUE TITLE
Server crashes under load

### ISSUE THREAD

**Issue by amoonrah** [davehorton/drachtio-server#98]
I created an app that :
replies with 200 ok to options
replies with 503 to sip invites after 6 invites, we take the call by creating a UAS.

call flow

SIPP -> SBC -> drachtio

If I ran the scenario once, all is good, if I run sipp at a rate of 10cps, dratchio server will crash anywhere between the 100th and the 500th calls

last output to console

drachtio: ../src/sip-dialog-controller.cpp:1668: std::shared_ptr<drachtio::SipDialog> drachtio::SipDialogController::clearIIP(nta_leg_t*): Assertion `it != m_mapLeg2IIP.end()' failed.
Aborted (core dumped)

attached SIPP scenario and NodeJS app code
https://gist.github.com/amoonrah/a8042d443c440ba389d17cf9abaaba1b.js
https://gist.github.com/amoonrah/28faa665a5dce3d51143e34055dd7fcf.js

**Comment by davehorton** [comment]
I don't see the attachments....maybe they are still uploading.

what version of drachtio server are you running?

**Comment by amoonrah** [comment]
v0.8.3-rc3

**Comment by amoonrah** [comment]
I updated the links

**Comment by davehorton** [comment]
If the test is easy enough to run, can you try it with v0.8.4-rc1 ?  I had a memory leak fix in that earlier release, but had to revert it because the fix could lead to a crash

**Comment by amoonrah** [comment]
yes, very easy, will compile and let you know, I should have downloaded the latest anyways.

**Comment by amoonrah** [comment]
I'm fairly new to git and this may sound a bit stupid

how do I clone the v0.8.4-rc1 release?

I did this git clone --depth=50 --branch=develop git://github.com/davehorton/drachtio-server.git

and it gave me v0.8.3-2-ga5bec5a6a (compiled it and it still crashes)

I downloaded the v0.8.4-rc1 archive from under releases and it doesn't have the dependencies

**Comment by davehorton** [comment]
just checkout and build the latest on the develop branch

**Comment by amoonrah** [comment]
yeah it still crashes

**Comment by davehorton** [comment]
ok, can I recreate without the SBC?  Can I just point your sipp script at drachtio that is running your app?  Or is there more involved?

**Comment by amoonrah** [comment]
you should be able to ... I'll try it here first

**Comment by amoonrah** [comment]
so if i point sipp against drachtio directly it's not crashing.

here is the difference

on the drachtio server, I have 10 ip addresses

when I point to the SBC, it spreads the calls across all 10 IPs

when I point to drachtio directly it's only pointing to one IP, so the calls are not spread across mulitple IPs.

**Comment by davehorton** [comment]
hmm.  any chance you can have the SBC spread across two addresses, and see if it still crashes?  It would make it a bit easier for me to recreate if that was the case?

Did you again see the same assertion?

**Comment by amoonrah** [comment]
Yes, i can do that, i will do it tomorrow when i have access.

If you want i can even get you access to the system.

**Comment by amoonrah** [comment]
that's what I got on the last crash yesterday

2019-10-01 18:56:18.498544 tport.c:3047 tport_deliver() tport_deliver(0xaf5810): msg 0x1224e00 (474 bytes) from udp/10.140.21.12:5060 next=(nil)
2019-10-01 18:56:18.498641 nta.c:3025 agent_recv_request() nta: received ACK sip:+14167604123@10.132.0.32:5060;user=phone;npdi=yes SIP/2.0 (CSeq 1)
2019-10-01 18:56:18.498803 nta.c:3165 agent_recv_request() nta: ACK (1) is going to INVITE (1)
2019-10-01 18:56:18.498910 SipDialogController::processCancelOrAck: ACK
Segmentation fault (core dumped)

=====================
this is what I got today when sending traffic to two IP addresses only
=====================
2019-10-02 11:07:02.260262 tport.c:3047 tport_deliver() tport_deliver(0x19254a0): msg 0x1b613e0 (473 bytes) from udp/10.140.21.12:5060 next=(nil)
2019-10-02 11:07:02.260357 nta.c:3025 agent_recv_request() nta: received ACK sip:+14167604123@10.132.0.30:5060;user=phone;npdi=yes SIP/2.0 (CSeq 1)
2019-10-02 11:07:02.260456 nta.c:3165 agent_recv_request() nta: ACK (1) is going to INVITE (1)
2019-10-02 11:07:02.260549 SipDialogController::processCancelOrAck: ACK
Segmentation fault (core dumped)

**Comment by davehorton** [comment]
ok, great.  So it looks like if I run your sipp scenario against a drachtio server listening on two IPs, and I use your test app, I should be able to recreate, correct?

Can you also show your drachtio.conf.xml config so I can mimic that?

**Comment by amoonrah** [comment]
correct

<drachtio>
	<monitoring>
		<prometheus port="9060">0.0.0.0</prometheus>
	</monitoring>

	

	    <admin port="9022" secret="cymru">0.0.0.0</admin>

	
	<sip>
	        

		<contacts></contacts>


		<spammers action="reject" tcp-action="discard">
			<header name="User-Agent">
				<value>sip-cli</value>
				<value>sipcli</value>
				<value>friendly-scanner</value>
			</header>
			<header>
				<value>sipvicious</value>
			</header>
		</spammers>

		

	</sip>

	<cdrs>true</cdrs>

	<logging>
		<console/>

	        
		<sofia-loglevel>9</sofia-loglevel>

		
		<loglevel>debug</loglevel>
	</logging>

</drachtio>

**Comment by davehorton** [comment]
I'm thinking about taking you up on your offer to troubleshoot this on your machine, if you are still open to that.  It might be the quickest way for me to troubleshoot, if we could coordinate on a time where you send calls.  What do you think?

**Comment by amoonrah** [comment]
we can definitely do that, if we can chat on the phone to coordinate, it would make things go much faster.

**Comment by davehorton** [comment]
sure, why don't you email me at daveh at drachtio.org to coordinate

**Comment by davehorton** [comment]
I think I see the issue.  You are trying to simulate a scenario where a UAC (played by your sipp script) route advances across several UACs, as each returns a 500.  You are using the drachtio server (a single instance) to stand in for _all_ the UASs.  That is, the drachtio server receives an initial INVITE with Call-ID X, rejects it, and then receives another INVITE with the same Call-ID X, because the UAC is simulating route advancing to the next UAS......its just that it always sends to the drachtio server since that is your UAS testbed.

This seems to create a problem when the following scenario happens:
- UAC sends INVITE with Call-ID X to drachtio
- drachtio rejects with 500
- _Before_ receiving the ACK from that transaction, the drachtio server receives another INVITE with the same call-id X (but different via branch), ie the UAC has route advanced and send the INVITE again.

It appears to be a sort of race condition where the second INVITE is received before the ACK from the first.

From the drachtio server perspective, since the call id and the From tags are the same on the first and second INVITEs, and because the ACK has not arrived to completed the first transaction, the second INVITE is taken to be an in-dialog request.

What drachtio _should_ do at this point is simply send you back a 491 Request Pending non-success to that second INVITE, because the first INVITE transaction is still outstanding.

However, drachtio tries to actually set up that second call.....but that eventually leads to the crash due to drachtio incorrectly tracking them as different dialogs.

The fix is going to be to properly return you a 491 in these race conditions, I think.  This may have a side affect of causing your sipp scenario to fail since you won't be expecting this.  But it does seem like the correct behavior on the drachtio server side.  Do you agree?  I can prepare a patch for you to test.

I'd like your help in testing this fix, but afterwards now that I understand what you are trying to accomplish, it might be better for you to run N instances of drachtio simultaneously, each using command line arguments to listen on different ports (or IP addresses, if you wish).  That will more closely simulate the environment you want, and eliminate the possibility of the race condition that is going to lead to occasional 491 responses.

**Comment by amoonrah** [comment]
Hey,

I didn’t realize that the same call ID is being sent, the sbc should be
generating a new call, for every new call.

Let me make sure that the call ID is unique per new invite and retest, if
it fixes it, great, and then I would recommend we check if the RFC has an
explanation for the different branches, if it does not fix the issue then :(

Thx
Ggb

**Comment by amoonrah** [comment]
ok so now I see what you meant, given that drachtio is hosting the multiple IPs, the SBC is sending the call to the next target which should be a new system, but because it's hosted on the same drachtio server, the race condition is occurring.

You said "From the drachtio server perspective, since the call id and the From tags are the same on the first and second INVITEs, and because the ACK has not arrived to completed the first transaction, the second INVITE is taken to be an in-dialog request."

Can the branch be also used to identify the dialog?

In a production environment the same server would not be used for the second route if the first route failed and a 491 would definitely be the proper response, however adding the branch to the combination (from/call id)  to identify the dialog would make it more resilient to scenarios like the one I'm using it for.

**Comment by davehorton** [comment]
The branch is used to match a response to a request.  It does not identify a dialog.  A dialog is identified by the combination of the Call-ID and From tag.  In that sense, the second INVITE correctly has a new branch value, since this is a new request.  And drachtio detects it a new request.  Since the Call-ID and From tag match, drachtio determines this is the same Dialog as the first invite.

**Comment by amoonrah** [comment]
Ok let me known when the patch is ready and  i give it a try.

**Comment by davehorton** [comment]
I checked in a fix on the head of the develop branch, so if you can rebuild with that and test it would be good.

**Comment by amoonrah** [comment]
it's not crashing anymore, I get the 491 request pending message instead :)

**Comment by davehorton** [comment]
ok, if that ruins your testbed, can you just multiple instances on the same server, listening on different ports then?

**Comment by amoonrah** [comment]
it doesn't ruin my test bed, as i'm not doing any load test, when I do 1 call and the sbcs advances it to the different IPs, there are no issues.

I discovered the crash, when I didn't give sipp the -m option and it ran with 10cps for a bit.

**Comment by amoonrah** [comment]
i'm glad I didn't give sipp the option, it help plug a crash :)

**Comment by davehorton** [comment]
Me too!  Is it ok to close this  issue now?

**Comment by amoonrah** [comment]
I will close it :)
